// Mapeo de notas técnicas y requisitos adicionales por actividad-documentación
// Este archivo se puede importar en el seed principal para poblar el campo notes

// Mapeo completo de notas técnicas y requisitos adicionales por actividad-documentación
// Todas las combinaciones del markdown están presentes, nota vacía si no hay nota específica
export const activityDocumentationNotes: Record<string, Record<string, string>> = {
  'Espacios Confinados': {
    'Certificado Médico para Espacios Confinados': 'Certificado Médico específico requerido para actividades en espacios confinados.',
    'Curso Específico Actividad que va a Realizar': 'Curso específico para la actividad que va a realizar en espacios confinados.',
    'Certificado Examen Práctico': 'Examen Práctico requerido para actividades en espacios confinados.',
  },
  'Lainera': {
    'Sicosensotécnico': 'Examen Sicosensotécnico Anual requerido para Lainera.'
  },
  'Thunderbolt': {
    'Sicosensotécnico': 'Examen Sicosensotécnico Anual requerido para Thunderbolt.'
  },
  'Alzahombre': {
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Curso Específico Actividad que va a Realizar': 'Curso específico para la actividad que va a realizar (vigencia 4 años).',
    'Hoja de vida conductor': '',
  },
  'Equipo Radiactivo 1era, 2da Y 3era': {
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Curso Específico Actividad que va a Realizar': 'Curso específico para la actividad que va a realizar (vigencia 4 años).',
  },
  'Ambulancia': {
    'Sicosensotécnico': 'Examen Sicosensotécnico Anual. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Hoja de vida conductor': 'No tener faltas con suspensión de licencia municipal en últimos 12 meses. Para suspensiones más antiguas presentar Carta de Compromiso. Antigüedad mínima 18 meses.',
  },
  'Perfolodos WS 1400': {
    'Sicosensotécnico': 'Examen Sicosensotécnico Anual. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Hoja de vida conductor': 'No tener faltas con suspensión de licencia municipal en últimos 12 meses. Para suspensiones más antiguas presentar Carta de Compromiso. Antigüedad mínima 18 meses.',
  },
  'Armador De Andamio': {
    'Curso Específico Actividad que va a Realizar': 'Curso específico para la actividad que va a realizar. Vigencia 4 años.',
    'Certificado Médico Trabajo Altura Física': 'Certificado Médico acreditando aptitud para trabajo en altura física.',
    'Certificado Examen Práctico': '',
    'Hoja de vida conductor': '',
  },
  'Autorizado Para Bloquear': {
    'Curso Específico Actividad que va a Realizar': 'Curso específico para la actividad que va a realizar. Vigencia 4 años.',
    'Certificado Examen Práctico': '',
    'Hoja de vida conductor': '',
  },
  'Buses': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Transporte pasajeros > 17 ocupantes. Lic A3 (Ley 19495) o A1 (ley 18290). Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Camión Ácido': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Aljibe CAT 773E': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camión Aljibe KOM 785 HD-7': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Tracto Camión': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Ampliroll': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Camión Articulado Dumper': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Camión Aspirador Alto Vacio': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Cama Baja Mack': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camión Combustible': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'DS 160 Curso Sustancia Peligrosa': 'DS 160 Curso de Sustancias Peligrosas emitido por Carabineros, Automovil Club, otras.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camión Catodos': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión 3/4': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Caex 773': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camión Caex 777': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Traslado Perforadora': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Traslado Palas': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camión Extracción CAT 785C': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camión Caex 789': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camión Fábrica': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Licencia de Manipulador de Explosivos': 'Licencia de Manipulador de Explosivos requerida.',
  },
  'Camión Fosero': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Camión Hidrolavador': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Lubricador': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camión Pluma Solo Camión': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Pluma Y Grua Pluma': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Camión Polvorín': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Licencia de Manipulador de Explosivos': 'Licencia de Manipulador de Explosivos requerida.',
  },
  'Camión De Sevicio': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Camión plataforma, camión de carga en general sin especificación. Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Sonda': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camión Tolva': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Camión plataforma, camión de carga en general sin especificación. Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Rampla (plano)': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Rotainer': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Desobstructor': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camioneta Combustible': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camioneta Polvorinera': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camioneta Rescate/Emergencia': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Camioneta Triple Cabina': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Camión Frontal CAT 992G': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Camión Frontal CAT 994F': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Cargador Frontal Otras Marcas': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Excavadora Balde/Pica Roca': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Excavadoras PC 5500': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Furgon': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Transporte de pasajeros hasta 9 ocupantes. Lic A3 - A2 Ley 19495 o A1 (Ley 18290). Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Grúa Horquilla': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Grúa Móvil': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Grúa Pluma Solo Grúa': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Grúa Puente': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Manipulador De Neumáticos CF': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Manipulador De Neumáticos GH': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Manipulador Telescópico': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Martillo Pica Roca': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Equipo estático de Chancado Primario. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Minibus': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Transporte pasajeros entre 10 y 17 ocupantes. Lic A3 - A2 Ley 19495 o A1 (Ley 18290). Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
  },
  'Minicargador': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Motoniveladora CAT 16M': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Perforadora MD6240': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Perforadora DM50': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Perforadora D755K': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Perforadora DMM2': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Retroexcavadoras': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Rigger': {
    'Curso Específico Actividad que va a Realizar': 'Curso específico para la actividad que va a realizar.',
  },
  'Rodillo': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Rotopala / Spreader': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': '',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Soldador': {
    'Curso Específico Actividad que va a Realizar': 'Curso específico para la actividad que va a realizar.',
  },
  'Sonda': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Tapapozos': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
    'Licencia de Manipulador de Explosivos': 'Licencia de Manipulador de Explosivos requerida.',
  },
  'Tractor De Orugas': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Tractor De Ruedas': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Vehículo Liviano': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 4 años. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
  },
  'Wheeldozer CAT 834G': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Cargador WA900': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Welldozer WD900': {
    'Sicosensotécnico': 'Sicosensotécnico: Cada 1 año. Certificado emitido por institución reconocida por MC. Ver Instructivo específico.',
    'Certificado Examen Práctico': 'Examen Práctico. Solo la primera vez.',
    'Hoja de vida conductor': 'Antigüedad mínima 18 meses. No tener faltas con suspensión de licencia municipal en últimos 12 meses.',
    'Certificado Curso Conducción a la defensiva': 'Curso de Conducción a la Defensiva cargado en Webcontrol.',
    'Capacitación teórica práctica - Zona Roja': 'Capacitación teórica práctica realizada por Gerencia Mina si equipo operará en Zona Roja.',
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Uso Cuchillo OLFA': {
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  },
  'Grua Portal': {
    'Curso Específico Equipo que va a Operar': 'Curso específico para el equipo que va a operar (vigencia 4 años).',
  }
};
